# Generated by Django 4.0.5 on 2022-06-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gotra_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gotra_name', models.CharField(max_length=30)),
            ],
        ),
    ]
