# Generated by Django 4.0.5 on 2022-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gotra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GotraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gotra_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'gotra_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='gotra_data',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
