# Generated by Django 4.0.5 on 2022-06-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_workdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('gotra', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('main_account', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('series_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customerdata',
                'managed': False,
            },
        ),
    ]
